# Generated by Django 2.1.7 on 2019-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteEscola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RA', models.CharField(max_length=50, verbose_name='RA')),
                ('Nome_Aluno', models.CharField(max_length=50, verbose_name='Nome_Aluno')),
                ('Sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('Genero', models.CharField(max_length=1, verbose_name='Genero')),
                ('Endereco', models.CharField(max_length=100, verbose_name='Endereco')),
                ('Telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Curso', models.CharField(max_length=50, verbose_name='Nome_Curso')),
                ('Nome_Disciplina', models.CharField(max_length=50, verbose_name='Nome_Disciplina')),
                ('Semestre', models.CharField(max_length=30, verbose_name='Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RP', models.CharField(max_length=50, verbose_name='RP')),
                ('Nome_Professor', models.CharField(max_length=50, verbose_name='Nome_Professor')),
                ('Sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('Genero', models.CharField(max_length=1, verbose_name='Genero')),
                ('Endereco', models.CharField(max_length=100, verbose_name='Endereco')),
                ('Telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('senha', models.CharField(max_length=50, verbose_name='senha')),
                ('Tipo_Usuario', models.IntegerField(verbose_name='Tipo_Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalhe_Curso',
        ),
    ]
